// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
//project1
// const SUPABASE_URL = "https://bkntvxbcrvixdezseghd.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbnR2eGJjcnZpeGRlenNlZ2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTExNDMsImV4cCI6MjA2NTc2NzE0M30.XY5PPt7g0hLx-o7xWjO-DduV0U2mJDZ1Wg0sPmg9xH4";

//porject2
const SUPABASE_URL = "https://nqntphlkxbjhkiemdstk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xbnRwaGxreGJqaGtpZW1kc3RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODIwMTMsImV4cCI6MjA3MTc1ODAxM30.tURis7zVlwcsOSAx4LL7Q2fVFOfQm0MElpcBV3nHKDI";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});